#!/usr/bin/env python3
"""Build the traceability matrix from the sources, rather than by hand.

The chain is requirement → case → spec → run. Each link already exists
somewhere: the requirements in the application's README, the cases in the
TestQuality exports, the specs in their own filenames and test titles. A
hand-written matrix is a fourth copy that starts correct and drifts, and a
matrix nobody trusts is worse than none — it is the same failure as DEF-15,
where a documented rule outlived the behaviour it described.

So this reads the three and writes the fourth. Run it after changing any of
them:

    python3 scripts/traceability.py --app ../alarm-configurator
"""

import argparse
import csv
import io
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def requirements(app_readme):
    """R-nn and its sentence, from the application's rules table."""
    text = io.open(app_readme, encoding='utf-8').read()
    found = {}
    for ident, rule in re.findall(r'^\| (R-\d+) \| (.+?) \| \w+ \|$', text, re.M):
        found[ident] = rule.strip()
    return found


def cases_from_csvs(directory):
    """Case id → (title, {requirements}, {tags}) from the TestQuality exports."""
    cases = {}
    for name in sorted(os.listdir(directory)):
        if not name.endswith('.csv'):
            continue
        for row in csv.reader(io.open(os.path.join(directory, name), encoding='utf-8')):
            if len(row) < 14 or not row[2].isdigit():
                continue
            case = int(row[2])
            title, reqs, tags = row[3].strip(), row[12] or '', row[13] or ''
            entry = cases.setdefault(case, [title, set(), set()])
            entry[1].update(re.findall(r'R-\d+', reqs))
            entry[2].update(t.strip() for t in tags.split(',') if t.strip())
    return cases


def cases_from_mapping(path):
    """The original ten, whose steps live in TestQuality and whose mapping lives here."""
    text = io.open(path, encoding='utf-8').read()
    found = {}
    for case, title, reqs in re.findall(r'^\| TC(\d+) \| (.+?) \| (.+?) \|$', text, re.M):
        found[int(case)] = [title.strip(), set(re.findall(r'R-\d+', reqs)), set()]
    return found


def specs(tests_dir):
    """Case id → [(spec file, test title)] for everything automated."""
    automated = defaultdict(list)
    for root, _dirs, files in os.walk(tests_dir):
        for name in files:
            if not name.endswith('.spec.ts'):
                continue
            path = os.path.join(root, name)
            relative = os.path.relpath(path, HERE).replace('\\', '/')
            for line in io.open(path, encoding='utf-8'):
                # Either quote style: a title containing an apostrophe is
                # written with double quotes, and matching only single ones
                # made those specs invisible to the matrix while they ran
                # perfectly well.
                match = re.search(r"""test\(\s*['\"](TC(\d+)[a-z]?):\s*(.+?)['\"]""", line)
                if match:
                    automated[int(match.group(2))].append((relative, match.group(1), match.group(3)))
    return automated


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--app', default=os.path.join(HERE, '..', 'alarm-configurator'))
    parser.add_argument('--out', default=os.path.join(HERE, 'docs', 'traceability.md'))
    args = parser.parse_args()

    app_readme = os.path.join(args.app, 'README.md')
    if not os.path.exists(app_readme):
        print(f'Cannot find the application README at {app_readme}', file=sys.stderr)
        return 1

    reqs = requirements(app_readme)
    cases = cases_from_mapping(os.path.join(HERE, 'docs', 'test-cases', 'requirement-mapping.md'))
    cases.update(cases_from_csvs(os.path.join(HERE, 'docs', 'test-cases')))
    automated = specs(os.path.join(HERE, 'tests'))

    by_requirement = defaultdict(list)
    for case, (title, case_reqs, tags) in cases.items():
        for requirement in case_reqs:
            by_requirement[requirement].append(case)

    uncovered = [r for r in sorted(reqs, key=lambda x: int(x[2:])) if not by_requirement.get(r)]
    unverified = [
        r
        for r in sorted(reqs, key=lambda x: int(x[2:]))
        if by_requirement.get(r) and not any(c in automated for c in by_requirement[r])
    ]
    covered = len(reqs) - len(uncovered)
    verified = covered - len(unverified)

    out = []
    w = out.append
    w('# Traceability matrix\n')
    w('Requirement → case → spec. Generated by '
      '[`scripts/traceability.py`](../scripts/traceability.py) from the three places '
      'these already live: the rules table in the application\'s README, the case '
      'exports in [`docs/test-cases/`](test-cases/), and the test titles in '
      '[`tests/`](../tests/). It is not maintained by hand, because a hand-kept '
      'fourth copy starts correct and drifts — which is DEF-15 one layer up.\n')
    w('## Where coverage stands\n')
    w('| | Count |')
    w('| --- | --- |')
    w(f'| Requirements | {len(reqs)} |')
    w(f'| With at least one case | {covered} |')
    w(f'| With at least one automated spec | {verified} |')
    w(f'| Cases designed | {len(cases)} |')
    w(f'| Cases automated | {len(automated)} |')
    w(f'| Specs | {sum(len(v) for v in automated.values())} |\n')

    # A "none" in the matrix is a fact without a reason, and the reasons are
    # decisions rather than data - so they are written down once, by hand, and
    # pointed at from here rather than guessed at by this script.
    w('Every case without a spec, and why, is in '
      '[not-automated.md](test-cases/not-automated.md). None of them is '
      'outstanding work: three are decisions about what a test can usefully '
      'assert, and one is a feature behind a paid tier, which is '
      '[out of scope](../README.md#what-is-not-under-test).\n')

    w('## The matrix\n')
    w('| Requirement | Cases | Automated as |')
    w('| --- | --- | --- |')
    for ident in sorted(reqs, key=lambda x: int(x[2:])):
        listed = sorted(by_requirement.get(ident, []))
        if not listed:
            w(f'| **{ident}** | — | **no case** |')
            continue
        case_text = ', '.join(f'TC{c}' for c in listed)
        spec_text = []
        for case in listed:
            for _path, label, _title in automated.get(case, []):
                spec_text.append(label)
        w(f'| {ident} | {case_text} | {", ".join(sorted(set(spec_text))) or "**none**"} |')

    if uncovered:
        w('\n## Requirements no case verifies\n')
        w('Listed so the gap is visible rather than implied.\n')
        w('| Requirement | Rule |')
        w('| --- | --- |')
        for ident in uncovered:
            w(f'| **{ident}** | {reqs[ident]} |')

    if unverified:
        w('\n## Requirements with a case but no spec\n')
        w('Designed, not automated. These are the next ones worth writing.\n')
        w('| Requirement | Cases |')
        w('| --- | --- |')
        for ident in unverified:
            w(f'| {ident} | {", ".join(f"TC{c}" for c in sorted(by_requirement[ident]))} |')

    w('\n## Cases with no requirement\n')
    orphans = sorted(c for c, (_t, r, _g) in cases.items() if not r)
    if orphans:
        w('A case that verifies nothing stated is either testing an undocumented '
          'rule or testing nothing. Both are worth knowing.\n')
        for case in orphans:
            w(f'- TC{case} — {cases[case][0]}')
    else:
        w('None. Every case names at least one requirement.')

    io.open(args.out, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print(f'{args.out}: {len(reqs)} requirements, {len(cases)} cases, '
          f'{sum(len(v) for v in automated.values())} specs')
    print(f'  {covered}/{len(reqs)} requirements have a case, {verified} have a spec')
    if uncovered:
        print(f'  no case at all: {", ".join(uncovered)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
